### ISSUE TITLE
Economic lifetime of a unit

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/SpineOpt.jl#601] opened 2023-04-12 08:04 UTC
There is now greater than constraint in economic lifetime of a unit. It should probably be equality to remove the unit after unit lifetime.

Also - the end of horizon for investments should be discussed further.

**Comment by clizbe** [comment] 2024-01-04 16:24
@datejada Do you know if we've fixed this yet? (Or related issues we can link it to?)

**Comment by datejada** [comment] 2024-01-05 07:21
@clizbe not yet since it will be covered on the changes for the multi-year investment, which is one of the tasks we are currently working on in WP4. I'll monitor this issue when those changes are merged into the main branch.

**Comment by DillonJ** [comment] 2024-01-05 11:21
Hi @datejada @clizbe just to note here that we discussed this a few times and there are use cases for the constraint being an equality, or an inequality - and in the case of an inequality, there are use cases for it being >= or <=

The most flexible thing to do here is to leave it to the user. The possibilities could be:
 - Introduce a new parameter which is `investment_lifetime_sense` which can be ==, >= or <=
 - or, introduce e.g. `min_investment_lifetime`, `max_investment_lifetime` and `strict_investment_lifetime`
 
 Depending on how we implement the economic representation of investments, one might also want to define an economic lifetime that is just used for calculation of annualised investments costs and does not result in the imposition of any constraints (which in this case are quite costly for performance). Also, there are other ways to achieve the functionalility without the lifetime constraint (e.g. the investment temporal_structure).

**Comment by clizbe** [comment] 2024-01-12 15:39
@datejada Is this related or a duplicate of #689?

**Comment by datejada** [comment] 2024-08-13 07:09
Closing this issue since it is duplicated of #689

**Closed by datejada** 2024-08-13 07:09 UTC
Labels: Zone: formulation, Type: improvement
