### ISSUE TITLE
User from Node constraint

### ISSUE THREAD

**Issue by shuo1990** [spine-tools/SpineOpt.jl#955] opened 2024-03-26 14:39 UTC
Hi,

I place my V2H charger in the User, and EV SOC in the Node. I have set the minimum SOC 10%. How can I set an additional constraint of <30% disallow the EV to discharge?

Kind regards
Shuo

**Comment by shuo1990** [comment] 2024-03-28 13:28
Thank you Antti.

Hopefully, my issue will be answered as soon as possible.

Kind regards,

Shuo



________________________________

**Comment by DillonJ** [comment] 2024-03-28 13:54
Duplicate of https://github.com/spine-tools/SpineOpt.jl/issues/954

**Closed by DillonJ** 2024-03-28 13:54 UTC
