### ISSUE TITLE
Fix_units_invested issue

### ISSUE THREAD

**Issue by fbozzolo** [spine-tools/SpineOpt.jl#589] opened 2023-04-03 10:47 UTC
Hi, I've been working on a renewable energy hub with a constant energy demand node, hydrogen and ammonia production and their respective storage. The investment optimization worked fine until I added the Fix_units_invested parameter to any unit. Even if I added the optimized unit size from the previous round as the parameter value the system appeared as "infeasible". 

I tried to make it work on a 5 hours system and it worked, but on my whole year optimization model, it didn't.

Any thoughts?

**Comment by DillonJ** [comment] 2023-04-20 13:58
I believe this is a duplicate of https://github.com/spine-tools/SpineOpt.jl/discussions/624

**Closed by DillonJ** 2023-04-20 13:58 UTC
